source 'http://rubygems.org'

gemspec path: File.expand_path(File.dirname(__FILE__) + '/../..')

group :development do
  gem 'better_errors', '~> 0.8.0'
  gem 'binding_of_caller', '~> 0.7.1'
  gem 'meta_request', '~> 0.2.5'
end