source 'http://rubygems.org'

gemspec path: File.expand_path(File.dirname(__FILE__) + '/../..')

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
  gem 'rack-insight'
end